services:
  ml-service:
    image: dockerfile
    ports:
      - "8000:8000"
    cpus: 3
    mem_limit: 1g
    environment:
      - MODEL_PATH=license_plate_detector.pt
      - INPUT_FOLDER=Vehicle License Plate List
    volumes:
      - ./Vehicle License Plate List:/app/Vehicle License Plate List